#pragma once
#ifndef __TARGETMOVEMENT__
#define __TARGETMOVEMENT__
enum TargetMovement
{
	IDLE,
	MOVE_RANDOMLY,
	PATROL,
	TAKING_DAMAGE,
	MOVE_TO_PLAYER,
	CLOSE_COMBAT_ATTACK,
	DEFEAT,
	FLEE,
	MOVE_TO_LOS,
	MOVE_TO_RANGE,
	MOVE_BEHIND_COVER,
	WAIT_BEHIND_COVER,
	RANGED_ATTACK

};
#endif /* defined (__TARGETMOVEMENT__) */